### ISSUE TITLE
Filecoin LSP

### ISSUE THREAD

**Issue by empea-careercriminal** [ChainSafe/filix#10]
- [ ] Integration of most valuable commands into Code Actions
- [ ] Visualise gas traces as an overlay
- [ ] Support Rust (some others as well, at least for Code Actions?)
