### ISSUE TITLE
Network Management

### ISSUE THREAD

**Issue by empea-careercriminal** [ChainSafe/filix#22]
Part of the toolbox that shall handle network management
- creating/configuring/restarting/etc. local devnets
- hooking to existing remote networks
- forking and running a sandbox

Related issues:
- [ ] Network Management - Local
- [ ] Network Management - Remote
- [ ] Network Management - Fork
- [ ] Network Management - Sandbox
